import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LANGUAGE_STORAGE_KEY = 'geosom-language';

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Common
    'common.search': 'Search Here',
    'common.loading': 'Loading...',
    'common.show': 'Show',
    'common.save': 'Save Changes',
    'common.cancel': 'Cancel',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.delete': 'Delete',
    'common.action': 'Action',
    'common.addNew': 'Add New',
    'common.noData': 'No data available in table',
    'common.showing': 'Showing',
    'common.to': 'to',
    'common.of': 'of',
    'common.entries': 'entries',
    'common.version': 'Version: 2.0.0 / MAJOR',
    'common.copyright': '2025© Geosom Technologies Solutions.',
    'common.welcome': 'Welcome',

    // Menu
    'menu.dashboard': 'Dashboard',
    'menu.services': 'Services',
    'menu.imports': 'Imports',
    'menu.warehouses': 'Warehouses',
    'menu.transports': 'Transports',
    'menu.expenses': 'Expenses',
    'menu.hr': 'HR',
    'menu.registration': 'Registration',
    'menu.reports': 'Reports And Analytics',
    'menu.settings': 'Settings',
    'menu.roles': 'Roles',
    'menu.users': 'Users',
    'menu.configurations': 'Configurations',
    'menu.commercial-chamber': 'Commercial Chamber',
    'menu.local-company': 'Local Company',
    'menu.transfer-document-9': 'Transfer Document Number 9',
    'menu.chamber-invoice': 'Chamber Invoice',
    'menu.performa': 'Performa',
    'menu.customer-file': 'Customer File',
    'menu.certificate-origin': 'Certificate of Origin',
    'menu.suppliers': 'Suppliers',
    'menu.orders': 'Orders',
    'menu.order-verification': 'Order Verification',
    'menu.order-reception': 'Order Reception',
    'menu.delivered-orders': 'Delivered Orders',
    'menu.document-9': 'Document No 9',
    'menu.document-4': 'Document No 4',
    'menu.clearance': 'Clearance',
    'menu.invoice-report': 'Invoice Report',
    'menu.products': 'Products',
    'menu.inventories': 'Inventories',
    'menu.warehouse': 'Warehouse',
    'menu.carriers': 'Carriers',
    'menu.associations': 'Associations',
    'menu.carrier-mode': 'Carrier Mode',
    'menu.routes': 'Routes',
    'menu.shipping-lines': 'Shipping Lines',
    'menu.logistics-files-operations': 'Logistics Files / Operations',
    'menu.transportation-management': 'Transportation Management',
    'menu.bulk-transportation-management': 'Bulk Transportation Management',
    'menu.car-reservations': 'Car Reservations',
    'menu.fleet-management': 'Fleet Management',
    'menu.transport-expense-requests': 'Expense Requests',
    'menu.purchase-management': 'Purchase Management',
    'menu.sales-management': 'Sales Management',
    'menu.accounting-system': 'Accounting System',
    'menu.transport-reporting-analytics': 'Reporting & Analytics',
    'menu.transport-configuration-admin': 'Configuration & Administration',
    'transport.modulePlaceholder': 'This section will display the corresponding module.',
    'menu.expense-categories': 'Expense Categories',
    'menu.expense': 'Expense',
    'menu.expense-allocation': 'Expense Allocation',
    'menu.other-expenses': 'Other Expenses',
    'menu.maritime-lines': 'Maritime Lines',
    'menu.personnel-file': 'Personnel File',
    'menu.payroll': 'Payroll',
    'menu.leave-management': 'Leave Management',
    'menu.attendance-management': 'Attendance Management',
    'menu.employees': 'Employees',
    'menu.contract-types': 'Contract Types',
    'menu.employee-professions': 'Employee Professions',
    'menu.employee-documents': 'Employee Documents',
    'menu.generate-payroll': 'Generate Payroll',
    'menu.payroll-approval': 'Payroll Approval',
    'menu.tax-rates': 'Tax Rates',
    'menu.leave-request': 'Leave Request',
    'menu.leave-types': 'Leave Types',
    'menu.leave-return-request': 'Leave Return Request',
    'menu.attendance': 'Attendance',
    'menu.clients': 'Clients',
    'clients.pageTitle': 'Manage clients',
    'clients.addButton': 'Add a new client',
    'clients.show': 'Show',
    'clients.entries': 'entries',
    'clients.searchLabel': 'Search:',
    'clients.colCompany': 'Company',
    'clients.colName': 'Name',
    'clients.colEmail': 'Email',
    'clients.colPhone': 'Phone',
    'clients.colAddress': 'Address',
    'clients.colAction': 'Action',
    'clients.empty': 'No data available',
    'clients.modalTitle': 'Add / Update client',
    'clients.fieldName': 'Client name',
    'clients.fieldCompany': 'Company name',
    'clients.fieldEmail': 'Email',
    'clients.fieldPhone': 'Phone',
    'clients.fieldAddress': 'Address',
    'clients.save': 'Save',
    'clients.selectClient': 'Select a client',
    'menu.bank': 'Bank',
    'menu.item-prices': 'Item Prices',
    'menu.goods-categories': 'Goods Categories',
    'menu.companies': 'Companies',
    'menu.import-reports': 'Import Reports',
    'menu.hr-reports': 'HR Reports',
    'menu.financial-reports': 'Financial Reports',
    'menu.services-reports': 'Services Reports',

    // Financial Reports
    'financial.title': 'Financial Reports',
    'financial.subtitle': 'All reports of the selected one',
    'financial.expenseReport': 'Expense Report',
    'financial.expenseReportDesc': 'View and analyze all expense transactions.',
    'financial.allocationReport': 'Expense Allocation Summary',
    'financial.allocationReportDesc': 'View and analyze expense allocation report.',
    'financial.profitReport': 'Monthly Profit Summary',
    'financial.profitReportDesc': 'View and analyze monthly service revenue, expenses, and profit.',
    'financial.backToReports': '← Back to reports',
    'financial.expenseReportTitle': 'Expense Report',
    'financial.viewAnalysis': 'View Analysis',
    'financial.print': 'Print',
    'financial.dateRange': 'Date Range',
    'financial.expenseCategories': 'Expense Categories',
    'financial.expenseType': 'Expense Type',
    'financial.search': 'Search',
    'financial.all': 'All',
    'financial.type': 'Type',
    'financial.category': 'Category',
    'financial.expense': 'Expense',
    'financial.amount': 'Amount',
    'financial.amountUSD': 'Amount USD($)',
    'financial.description': 'Description',
    'financial.status': 'Status',
    'financial.date': 'Date',
    'financial.total': 'Total:',
    'financial.noExpenses': 'No expenses found',
    'financial.allocationTitle': 'Expense Report',
    'financial.viewDetail': 'View Detail',
    'financial.printSummary': 'Print Summary Report',
    'financial.month': 'Month',
    'financial.totalExpenses': 'Total Expenses',
    'financial.totalAllocation': 'Total Allocation',
    'financial.balance': 'Balance',
    'financial.action': 'Action',
    'financial.profitTitle': 'Monthly Profit Summary',
    'financial.year': 'Year:',
    'financial.totalServices': 'Total Services',
    'financial.totalHRExpenses': 'Total HR Expenses',
    'financial.profit': 'Profit',
    'financial.percentage': '% Percentage',
    'financial.overallTotal': 'Overall Total:',

    // Services Reports
    'services.title': 'Services Reports',
    'services.subtitle': 'All reports of the selected one',
    'services.localCompanyReport': 'Local Company Report',
    'services.localCompanyDesc': 'This report provides details about the local company.',
    'services.chamberServices': 'Chamber Services',
    'services.chamberServicesDesc': 'Provides detailed information about chamber services.',
    'services.backToReports': '← Back to reports',
    'services.ordersReport': 'Orders Report',
    'services.dateRange': 'Date Range',
    'services.client': 'Client',
    'services.search': 'Search',
    'services.ref': 'REF',
    'services.mobile': 'Mobile',
    'services.goodsDescription': 'Goods Of Description',
    'services.serviceFee': 'Service Fee',
    'services.creationDate': 'Creation Date',
    'services.createdBy': 'Created By',
    'services.action': 'Action',
    'services.total': 'Total:',
    'services.localCompanyTitle': 'Local Company Report',
    'services.sellingCompany': 'Selling Company',
    'services.sourceDestination': 'Source and Destination',
    'services.descriptionOfGoods': 'Description of Goods',
    'services.fileFee': 'File Fee',
    'services.truckQuantity': 'Truck Loading Quantity',
    'services.totalProfit': 'Total Profit',

    // Commercial Chamber
    'commercial.title': 'Manage Commercial List',
    'commercial.client': 'Client',
    'commercial.responsible': 'Responsible',
    'commercial.goodsDescription': 'Description of Goods',
    'commercial.servicesTotal': 'Services Total',
    'commercial.serviceCharge': 'Service Charge',
    'commercial.bankFee': 'Bank Fee',
    'commercial.transport': 'Transport',
    'commercial.total': 'Total',
    'commercial.createdBy': 'Created By',
    'commercial.print': 'Print',
    'commercial.addUpdate': 'Add/Update Commercial',
    'commercial.editEntry': 'Edit commercial record',
    'commercial.commercialInvoiceNo': 'Commercial Invoice No',
    'commercial.commercialInvoiceDate': 'Commercial Invoice Date',
    'commercial.purchaseOrderNo': 'Purchase Order No',
    'commercial.purchaseOrderDate': 'Purchase Order Date',
    'commercial.chamberServiceAmount': 'Chamber Service Amount',
    'commercial.quantity': 'Quantity',
    'commercial.unitPrice': 'Unit Price Commercial Invoice',
    'commercial.percentage': 'Percentage %',
    'commercial.tell': 'Tell',
    'commercial.timno': 'Timno',
    'commercial.customerDocument': 'Customer Document',
    'commercial.chamberDocument': 'Chamber Document',
    'commercial.chamberInvoice': 'Chamber Invoice',
    'commercial.commercialInvoice': 'Commercial Invoice',
    'commercial.packingList': 'Packing List',
    'commercial.truckWayBill': 'Truck Way Bill',
    'commercial.originalCertificate': 'Original Certificate',
    'commercial.certificateFee': 'Certificate Fee',
    'commercial.chooseFile': 'Choose File',
    'commercial.previous': 'Previous',
    'commercial.next': 'Next',
    'commercial.finish': 'Finish',
    'commercial.pageSubtitle': 'Track commercial files, FDJ amounts and related documents.',
    'commercial.modalBadge': 'Commercial chamber',
    'commercial.step1Label': 'Case details',
    'commercial.step2Label': 'Documents',
    'commercial.optionalDocumentsNote':
      'Note: The following documents are optional. Please ensure they are valid and in good condition.',
    'commercial.responsiblePlaceholder': "Manager's name",

    // Local Company
    'local.title': 'Manage local company list',
    'local.localCompany': 'Local Company',
    'local.fullLocalCompany': 'Full Local Company',
    'local.client': 'Client',
    'local.sourceDestination': 'Source Destination',
    'local.vendorCompany': 'Vendor Company',
    'local.goodsDescription': 'Description of goods',
    'local.purchasingCompany': 'Purchasing Company',
    'local.fileFee': 'File Fee',
    'local.quantity': 'Quantity',
    'local.truckLoadingQuantity': 'Truck Loading Quantity',
    'local.addUpdate': 'Add/Update Local Company',
    'local.closureDate': 'Closure Date',
    'local.billOfLoading': 'Bill of loading',
    'local.declarationS': 'Declaration S',
    'local.declarationE': 'Declaration E',
    'local.transitFee': 'Transit Fee',
    'local.serviceFee': 'Service Fee',
    'local.escortFee': 'Escort Fee',
    'local.total': 'Total',
    'local.deliveryOrder': 'Delivery Order',
    'local.transferDocS': 'Transfer Document S',
    'local.numero9': 'Numero 9',
    'local.numero9Price': 'Numero 9 Price',
    'local.numero4': 'Numero 4',
    'local.numero4Price': 'Numero 4 Price',
    'local.tiCancellation': 'TI Cancellation',
    'local.declarationCancellation': 'Declaration Cancellation S or E',
    'local.transfer': 'Transfer',
    'local.declarationCancellationPrice': 'Cancellation Price for Declaration S, E or T',
    'local.fullScannedDocument': 'Full Scanned Document',
    'local.printService': 'Print Service',
    'local.next': 'Next',
    'local.documentsNote': 'The following documents are required. Please ensure they are valid and in good condition.',
    'local.fullCompanyNotice': 'Here we displayed all steps included local company completed from document 9 transfer, we exclude non-completed steps.',
    'local.modalBadge': 'Local company',
    'local.step1Label': 'Case details',
    'local.step2Label': 'Documents',
    'local.vendorCompanyPlaceholder': 'Enter the selling company name',
    'local.viewRecord': 'View record',
    'local.editRecord': 'Edit record',
    'local.deleteModalTitle': 'Delete this service invoice?',
    'local.deleteTypeClientName': 'Type the client name exactly to confirm deletion.',
    'local.deleteNotAllowedAge': 'This record is older than 30 days and can only be archived by an administrator.',
    'local.deleteConfirm': 'Delete permanently',

    // Transfer Document 9
    'transfer9.title': 'Manage Transfer Document Number 9',
    'transfer9.recipientName': 'Recipient Name',
    'transfer9.destination': 'Destination',
    'transfer9.declarationEntry': 'Decl. Entry ZF/FZ/Entrepôt',
    'transfer9.goodsDescription': 'Description of Goods',
    'transfer9.destinationName': 'Destination Name/Declarant',
    'transfer9.declaredValue': 'Declared Value',
    'transfer9.addUpdate': 'Add/Update Number 9 Transfer',
    'transfer9.placeholderEnter': 'Enter…',
    'transfer9.step1RequiredError': 'Please fill in recipient / declarant and destination name.',
    'transfer9.processOngoing': 'The process of this form is currently ongoing.',
    'transfer9.requireAllSteps': 'Require All Steps',
    'transfer9.codeNo': 'Code No',
    'transfer9.licenseCode': 'License Code',
    'transfer9.fzOperatorName': 'FZ/Warehouse Operator Name',
    'transfer9.summitNumber': 'Summit/Repertoire Number',
    'transfer9.doNumber': 'D/O Number',
    'transfer9.entryQuantity': 'Entry Quantity',
    'transfer9.vesselName': 'Vessel Name',
    'transfer9.arrivalDate': 'Arrival Date',
    'transfer9.nifCode': 'NIF Code',
    'transfer9.shippingNumber': 'Shipping Number',
    'transfer9.originCountry': 'Country of Origin',
    'transfer9.voyageNumber': 'Voyage Number',
    'transfer9.fiscalReg': 'Fiscal Registration',
    'transfer9.hsCode': 'HS Code',
    'transfer9.exitQuantity': 'Exit Quantity',
    'transfer9.grossWeight': 'Gross Weight',
    'transfer9.exitPoint': 'Exit Point',
    'transfer9.next': 'Next',
    'transfer9.finish': 'Finish',
    'transfer9.actionsMenu': 'Row actions',
    'transfer9.actionView': 'View',
    'transfer9.actionViewDocument': 'View document',
    'transfer9.actionEdit': 'Edit',
    'transfer9.actionDelete': 'Delete',
    'transfer9.actionDownloadPdf': 'Download PDF',

    // Chamber Invoice
    'chamberInvoice.title': 'CHAMBER INVOICE',
    'chamberInvoice.details': 'Commercial Invoice Details',
    'chamberInvoice.consignee': 'Consignee',
    'chamberInvoice.tin': 'TIN',
    'chamberInvoice.tel': 'TEL',
    'chamberInvoice.sourceDestination': 'Source/Destination',
    'chamberInvoice.commercialRelation': 'Commercial Relationship',
    'chamberInvoice.consignmentLocation': 'Consignment Location',
    'chamberInvoice.invoiceNumber': 'Invoice Number',
    'chamberInvoice.invoiceDate': 'Invoice Date',
    'chamberInvoice.salesConditions': 'Sales Conditions (Incoterm)',
    'chamberInvoice.purchaseOrder': 'Purchase Order',
    'chamberInvoice.appReferenceNumber': 'APP Reference Number',
    'chamberInvoice.paymentConditions': 'Payment Conditions',
    'chamberInvoice.invoiceCurrency': 'Invoice Currency',
    'chamberInvoice.expedition': 'Expedition',
    'chamberInvoice.swiftCode': 'SWIFT Code',
    'chamberInvoice.loadingPort': 'Loading Port',
    'chamberInvoice.finalDestination': 'Final Destination',
    'chamberInvoice.bankDetails': 'Bank Details',
    'chamberInvoice.bankAccount': 'Bank Account',
    'chamberInvoice.intermediateBank': 'Intermediate Bank',
    'chamberInvoice.currency': 'Currency',
    'chamberInvoice.goodsDescription': 'Description of Goods',
    'chamberInvoice.description': 'Description',
    'chamberInvoice.descriptionPlaceholder': 'e.g. RBD PALM OIL 20 L — full product description',
    'chamberInvoice.hsCode': 'HS Code',
    'chamberInvoice.origin': 'Origin',
    'chamberInvoice.unit': 'Unit',
    'chamberInvoice.qty': 'Qty',
    'chamberInvoice.unitPrice': 'Unit Price (USD$)',
    'chamberInvoice.totalAmount': 'Total Amount (USD$)',

    // Performa
    'performa.title': 'Performa',
    'performa.addNew': 'Add New Entry',
    'performa.print': 'Print',
    'performa.buyer': 'Buyer',
    'performa.vendor': 'Vendor',
    'performa.performaCode': 'Performa Code',
    'performa.tinNo': 'Tin no',
    'performa.addUpdate': 'Add/Update Performa',
    'performa.sourceDestination': 'Source and Destination',
    'performa.goodsTable': 'Goods Description Table',
    'performa.descriptionOfGoods': 'Description of Goods',
    'performa.hsCode': 'HS CODE',
    'performa.qty': 'Qty',
    'performa.unitPrice': 'Unit Price',
    'performa.totalUnitPrice': 'Total Unit Price',
    'performa.origin': 'Origin',
    'performa.expedition': 'Expedition',
    'performa.swiftCode': 'Swift Code',
    'performa.loadingPort': 'Loading Port',
    'performa.finalDestination': 'Final Destination',
    'performa.payment': 'Payment',
    'performa.bank': 'Bank',
    'performa.fiscalIdNumber': 'Tax ID Number',
    'performa.saveChanges': 'Save Changes',

    // Customer File
    'customerFile.title': 'Manage Customer Files',
    'customerFile.addNew': 'Add New',
    'customerFile.customerName': 'Customer Name',
    'customerFile.fileNumber': 'File Number',
    'customerFile.description': 'Description',
    'customerFile.fileType': 'File Type',
    'customerFile.billOfLading': 'BL',
    'customerFile.destination': 'Destination',
    'customerFile.createdBy': 'Created By',
    'customerFile.addUpdate': 'Add/Update Customer File',
    'customerFile.rtaOperation': 'RTA Operation',
    'customerFile.transitNumber': 'Transit Number',
    'customerFile.arrivalDate': 'Arrival Date',
    'customerFile.loadingNumber': 'Loading Number',
    'customerFile.freightForwarder': 'Freight Forwarder',
    'customerFile.eslOperation': 'ESL Operation',
    'customerFile.taxId': 'TIN Number',
    'customerFile.voyageNumber': 'Voyage Number',
    'customerFile.receivedDate': 'Received Date',
    'customerFile.shippingLine': 'Shipping Line',
    'customerFile.save': 'Save',

    // Certificate of Origin
    'certificateOrigin.title': 'Certificate of Origin',
    'certificateOrigin.addNew': 'Add New',
    'certificateOrigin.client': 'Client',
    'certificateOrigin.description': 'Description',
    'certificateOrigin.destination': 'Destination',
    'certificateOrigin.hsCode': 'Code HS',
    'certificateOrigin.addUpdate': 'Add/Update Certificate of Origin',
    'certificateOrigin.transportType': 'Transport Type',
    'certificateOrigin.originProduct': 'Product of Origin',
    'certificateOrigin.declarationForm': 'Declaration Form',
    'certificateOrigin.taxIdNif': 'Tax ID (NIF)',
    'certificateOrigin.telephone': 'Telephone',
    'certificateOrigin.mt': 'MT',
    'certificateOrigin.grossWeight': 'Gross Weight',
    'certificateOrigin.save': 'Save',

    // Login
    'login.title': 'GEOSOM Transit',
    'login.sectorLabel': 'Transit & transport',
    'login.subtitle': 'Complete transit management solution for logistics, warehousing, and delivery operations',
    'login.welcomeBack': 'Welcome Back',
    'login.continueMessage': 'Please login to your account to continue',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.rememberMe': 'Remember Me',
    'login.forgotPassword': 'Forgot Password?',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing In...',
    'login.invalidCredentials': 'Invalid credentials. Please try again.',
    'login.signInByKey': 'Sign in by key',

    // Dashboard
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.totalExpenses': 'Total Expenses',
    'dashboard.deliveredOrders': 'Delivered Orders',
    'dashboard.completed': 'Completed',
    'dashboard.pending': 'Pending',
    'dashboard.lastMonth': 'Last Month',
    'dashboard.increased': 'Increased',
    'dashboard.decreased': 'Decreased',
    'dashboard.employeeGenderDistribution': 'Employee Gender Distribution',
    'dashboard.female': 'Female',
    'dashboard.male': 'Male',
    'dashboard.residenceDistribution': 'Residence Distribution',
    'dashboard.citizen': 'citizen',
    'dashboard.foreign': 'Foreign',

    // Roles
    'roles.title': 'Manage User Roles',
    'roles.roleName': 'Role Name',
    'roles.description': 'Description',
    'roles.addRole': 'Add New Role',
    'roles.editRole': 'Edit Role',

    // Users
    'users.title': 'Manage Users',
    'users.username': 'Username',
    'users.role': 'Role',
    'users.email': 'Email',
    'users.status': 'Status',
    'users.active': 'Active',

    // Configurations
    'config.baseSettings': 'Base Settings',
    'config.hrResources': 'Human Resources',
    'config.payroll': 'Payroll',
    'config.presence': 'Presence',
    'config.auth': 'Authentifications',
    'config.security': 'Account and Security Policy',
    'config.external': 'External Services',
    'config.manageApi': 'Manage API',
    'config.integrations': 'Integrations',
    'config.deleteAccount': 'Delete Account',
    'config.companyName': 'Company Name',
    'config.address': 'Address',
    'config.phone': 'Company Phone Number',
    'config.freightRate': 'Freight Rate',
    'config.units': 'Units',
    'config.ciAmount': 'Current CI Amount',
    'config.currency': 'Currency Symbol',
    'config.decimals': 'Decimals',
    'config.employeePrefix': 'Employee ID Prefix',
    'config.welcomeMessage': 'Enable welcome message on startup',
    'config.djfRate': 'Dollar to DJF Exchange Rate',
    'config.imageConfig': 'Image Configuration',
    'config.letterHead': 'Letter Head',
    'config.footerLogo': 'Footer Logo',
    'config.signatureLogo': 'Signature Logo',
    'config.chooseFile': 'Choose File',
    'config.noFileChosen': 'No file chosen',
    'config.payrollTitle': 'Payroll Settings',
    'config.payrollStart': 'Payroll Start Day',
    'config.payrollEnd': 'Payroll End Day',
    'config.absenceThreshold': 'High Absence Threshold (default 5)',
    'config.loginLimits': 'Enable login limits',
    'config.passwordExpiry': 'Enable password expiration',
    'config.detailedLogging': 'Enable detailed logging and sensitive actions',

    // Profile
    'profile.superAdmin': 'Super Admin',
    'profile.logout': 'Logout',
    'profile.english': 'English',
    'profile.french': 'French',
    'profile.arabic': 'Arabic',
    'layout.welcomeMessage': 'We are delighted to have you back! Explore your dashboard for the latest insights and actions',
  },
  fr: {
    // Common
    'common.search': 'Rechercher ici',
    'common.loading': 'Chargement...',
    'common.show': 'Afficher',
    'common.save': 'Enregistrer les modifications',
    'common.cancel': 'Annuler',
    'common.add': 'Ajouter',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.delete': 'Supprimer',
    'common.action': 'Action',
    'common.addNew': 'Ajouter Nouveau',
    'common.noData': 'Aucune donnée disponible dans le tableau',
    'common.showing': 'Affichage de',
    'common.to': 'à',
    'common.of': 'sur',
    'common.entries': 'entrées',
    'common.version': 'Version: 2.0.0 / MAJEUR',
    'common.copyright': '2025© Geosom Technologies Solutions.',
    'common.welcome': 'Bienvenue',

    // Menu
    'menu.dashboard': 'Tableau de bord',
    'menu.services': 'Services',
    'menu.imports': 'Importations',
    'menu.warehouses': 'Entrepôts',
    'menu.transports': 'Transports',
    'menu.expenses': 'Dépenses',
    'menu.hr': 'RH',
    'menu.registration': 'Inscription',
    'menu.reports': 'Rapports et Analyses',
    'menu.settings': 'Paramètres',
    'menu.roles': 'Rôles',
    'menu.users': 'Utilisateurs',
    'menu.configurations': 'Configurations',
    'menu.commercial-chamber': 'Chambre Commerciale',
    'menu.local-company': 'Entreprise locale',
    'menu.transfer-document-9': 'Transfert Document Numéro 9',
    'menu.chamber-invoice': 'Facture de Chambre',
    'menu.performa': 'Formulaire',
    'menu.customer-file': 'Fichier Client',
    'menu.certificate-origin': 'Certificat Original',
    'menu.suppliers': 'Fournisseurs',
    'menu.orders': 'Commandes',
    'menu.order-verification': 'Vérification de la Commande',
    'menu.order-reception': 'Réception de la Commande',
    'menu.delivered-orders': 'Commandes livrées',
    'menu.document-9': 'Document N° 9',
    'menu.document-4': 'Document N° 4',
    'menu.clearance': 'DÉMERRAGE',
    'menu.invoice-report': 'Rapport de Facture',
    'menu.products': 'Produits',
    'menu.inventories': 'Inventaires',
    'menu.warehouse': 'Entrepôt',
    'menu.carriers': 'Transporteurs',
    'menu.associations': 'Associations',
    'menu.carrier-mode': 'Mode transporteurs',
    'menu.routes': 'Itinéraires',
    'menu.shipping-lines': 'Lignes maritimes',
    'menu.logistics-files-operations': 'Dossiers logistiques / Opérations',
    'menu.transportation-management': 'Gestion du transport',
    'menu.bulk-transportation-management': 'Gestion du transport en vrac',
    'menu.car-reservations': 'Réservations de véhicules',
    'menu.fleet-management': 'Gestion de flotte',
    'menu.transport-expense-requests': 'Demandes de dépenses',
    'menu.purchase-management': 'Gestion des achats',
    'menu.sales-management': 'Gestion des ventes',
    'menu.accounting-system': 'Système comptable',
    'menu.transport-reporting-analytics': 'Rapports et analyses',
    'menu.transport-configuration-admin': 'Configuration et administration',
    'transport.modulePlaceholder': 'Le contenu de ce module sera affiché ici.',
    'menu.expense-categories': 'Catégories de Dépenses',
    'menu.expense': 'Dépense',
    'menu.expense-allocation': 'Allocation des Dépenses',
    'menu.other-expenses': 'Autres dépenses',
    'menu.maritime-lines': 'Lignes maritimes',
    'menu.personnel-file': 'Dossier personnel',
    'menu.payroll': 'Paie',
    'menu.leave-management': 'Gestion des congés',
    'menu.attendance-management': 'Gestion de l\'assiduité',
    'menu.employees': 'Employés',
    'menu.contract-types': 'Types de contrat',
    'menu.employee-professions': 'Professions des employés',
    'menu.employee-documents': 'Documents des employés',
    'menu.generate-payroll': 'Générer la paie',
    'menu.payroll-approval': 'Approbation de la paie',
    'menu.tax-rates': 'Taux d\'imposition',
    'menu.leave-request': 'Demande de congé',
    'menu.leave-types': 'Types de congé',
    'menu.leave-return-request': 'Demande de retour de congé',
    'menu.attendance': 'Présence',
    'menu.clients': 'Clients',
    'clients.pageTitle': 'Gérer les clients',
    'clients.addButton': 'Ajouter un nouveau client',
    'clients.show': 'Afficher',
    'clients.entries': 'entrées',
    'clients.searchLabel': 'Recherche :',
    'clients.colCompany': 'Entreprise',
    'clients.colName': 'Nom',
    'clients.colEmail': 'Email',
    'clients.colPhone': 'Téléphone',
    'clients.colAddress': 'Adresse',
    'clients.colAction': 'Action',
    'clients.empty': 'Aucune donnée disponible',
    'clients.modalTitle': 'Ajouter / Mettre à jour le client',
    'clients.fieldName': 'Nom du client',
    'clients.fieldCompany': "Nom de l'entreprise",
    'clients.fieldEmail': 'Email',
    'clients.fieldPhone': 'Téléphone',
    'clients.fieldAddress': 'Adresse',
    'clients.save': 'Enregistrer',
    'clients.selectClient': 'Choisir un client',
    'menu.bank': 'Banque',
    'menu.item-prices': 'Prix des Articles',
    'menu.goods-categories': 'Catégories de biens',
    'menu.companies': 'Entreprises',
    'menu.import-reports': 'Rapports d\'importation',
    'menu.hr-reports': 'Rapports RH',
    'menu.financial-reports': 'Rapports financiers',
    'menu.services-reports': 'Rapport des services',

    // Financial Reports
    'financial.title': 'Rapports Financiers',
    'financial.subtitle': 'Tous les rapports de celui sélectionné',
    'financial.expenseReport': 'Rapport des dépenses',
    'financial.expenseReportDesc': 'Afficher et analyser toutes les transactions de dépenses.',
    'financial.allocationReport': 'Résumé de l\'allocation des dépenses',
    'financial.allocationReportDesc': 'Afficher et analyser le rapport d\'allocation des dépenses.',
    'financial.profitReport': 'Résumé mensuel des bénéfices',
    'financial.profitReportDesc': 'Afficher et analyser les revenus mensuels des services, les dépenses et les bénéfices.',
    'financial.backToReports': '← Retour aux rapports',
    'financial.expenseReportTitle': 'Rapport des Dépenses',
    'financial.viewAnalysis': 'Voir les Analyses',
    'financial.print': 'Imprimer',
    'financial.dateRange': 'Plage de dates',
    'financial.expenseCategories': 'catégories des dépenses',
    'financial.expenseType': 'Type de Dépense',
    'financial.search': 'Rechercher',
    'financial.all': 'All',
    'financial.type': 'Type de Dépense',
    'financial.category': 'catégories des dépenses',
    'financial.expense': 'Dépense',
    'financial.amount': 'Montant',
    'financial.amountUSD': 'Amount USD($)',
    'financial.description': 'Description',
    'financial.status': 'Statut',
    'financial.date': 'Date',
    'financial.total': 'Total:',
    'financial.noExpenses': 'Aucune dépense trouvée',
    'financial.allocationTitle': 'Rapport des Dépenses',
    'financial.viewDetail': 'Voir en détail',
    'financial.printSummary': 'Imprimer le Rapport Résumé',
    'financial.month': 'Mois',
    'financial.totalExpenses': 'Montant total des dépenses',
    'financial.totalAllocation': 'Allocation totale',
    'financial.balance': 'Solde',
    'financial.action': 'Action',
    'financial.profitTitle': 'Monthly Profit Summary',
    'financial.year': 'Year:',
    'financial.totalServices': 'Total Services',
    'financial.totalHRExpenses': 'Total HR Expenses',
    'financial.profit': 'Profit',
    'financial.percentage': '% Percentage',
    'financial.overallTotal': 'Overall Total:',

    // Services Reports
    'services.title': 'Rapports des Services',
    'services.subtitle': 'Tous les rapports de celui sélectionné',
    'services.localCompanyReport': 'Rapport de l\'entreprise locale',
    'services.localCompanyDesc': 'Ce rapport fournit des détails sur l\'entreprise locale.',
    'services.chamberServices': 'Services de la chambre',
    'services.chamberServicesDesc': 'Fournit des informations détaillées sur les services de la chambre.',
    'services.backToReports': '← Retour aux rapports',
    'services.ordersReport': 'Rapport des commandes',
    'services.dateRange': 'Plage de dates',
    'services.client': 'Client',
    'services.search': 'Rechercher',
    'services.ref': 'REF',
    'services.mobile': 'Mobile',
    'services.goodsDescription': 'Goods Of Description',
    'services.serviceFee': 'Frais de service',
    'services.creationDate': 'Date de création',
    'services.createdBy': 'Créé par',
    'services.action': 'Action',
    'services.total': 'Total:',
    'services.localCompanyTitle': 'Local Company Report',
    'services.sellingCompany': 'Entreprise vendeuse',
    'services.sourceDestination': 'Source et Destination',
    'services.descriptionOfGoods': 'Description of Goods',
    'services.fileFee': 'Frais de Dossier',
    'services.truckQuantity': 'Quantité de chargement du camion',
    'services.totalProfit': 'Total Profit',

    // Commercial Chamber
    'commercial.title': 'Gérer la liste des commerciaux',
    'commercial.client': 'Client',
    'commercial.responsible': 'Responsable',
    'commercial.goodsDescription': 'Description des marchandises',
    'commercial.servicesTotal': 'Total des services',
    'commercial.serviceCharge': 'Montant du Service Client',
    'commercial.bankFee': 'Bank commission fee',
    'commercial.transport': 'Montant du transport',
    'commercial.total': 'Total',
    'commercial.createdBy': 'Créé par',
    'commercial.print': 'Imprimer',
    'commercial.addUpdate': 'Ajouter/Mettre à jour Commercial',
    'commercial.editEntry': 'Modifier le dossier commercial',
    'commercial.commercialInvoiceNo': 'Commercial Invoice No',
    'commercial.commercialInvoiceDate': 'Commercial Invoice Date',
    'commercial.purchaseOrderNo': 'Purchase Order No',
    'commercial.purchaseOrderDate': 'Purchase Order Date',
    'commercial.chamberServiceAmount': 'Chamber Service Amount',
    'commercial.quantity': 'Quantité',
    'commercial.unitPrice': 'Unit Price Commercial Invoice',
    'commercial.percentage': 'Percentage %',
    'commercial.tell': 'Tell',
    'commercial.timno': 'Timno',
    'commercial.customerDocument': 'Customer Document',
    'commercial.chamberDocument': 'Document de la chambre',
    'commercial.chamberInvoice': 'Facture de la chambre',
    'commercial.commercialInvoice': 'Commerical Invoice',
    'commercial.packingList': 'Liste de colisage',
    'commercial.truckWayBill': 'Truck way bill',
    'commercial.originalCertificate': 'Original Certificate',
    'commercial.certificateFee': 'Certificate Fee',
    'commercial.chooseFile': 'Choisir un fichier',
    'commercial.previous': 'Précédent',
    'commercial.next': 'Suivant',
    'commercial.finish': 'Terminer',
    'commercial.pageSubtitle': 'Suivi des dossiers, montants FDJ et documents associés.',
    'commercial.modalBadge': 'Chambre commerciale',
    'commercial.step1Label': 'Infos dossier',
    'commercial.step2Label': 'Documents',
    'commercial.optionalDocumentsNote':
      'Note : les documents ci-dessous sont facultatifs. Vérifiez qu\'ils sont valides et en bon état.',
    'commercial.responsiblePlaceholder': 'Nom du responsable',

    // Local Company
    'local.title': 'Gérer la liste des entreprises locales',
    'local.localCompany': 'Local Company',
    'local.fullLocalCompany': 'Full Local Company',
    'local.client': 'Client',
    'local.sourceDestination': 'Source et Destination',
    'local.vendorCompany': 'Nom de l\'entreprise vendeuse',
    'local.goodsDescription': 'Description des marchandises',
    'local.purchasingCompany': 'Entreprise acheteuse',
    'local.fileFee': 'Frais de dossier',
    'local.quantity': 'Quantité',
    'local.truckLoadingQuantity': 'Quantité de chargement du camion',
    'local.addUpdate': 'Ajouter/Mettre à jour l\'entreprise locale',
    'local.closureDate': 'Date de clôture',
    'local.billOfLoading': 'Bill of loading',
    'local.declarationS': 'Déclaration S',
    'local.declarationE': 'Déclaration E',
    'local.transitFee': 'Frais de transit',
    'local.serviceFee': 'Frais de service',
    'local.escortFee': 'Frais d\'escorte',
    'local.total': 'Total',
    'local.deliveryOrder': 'Ordre de livraison',
    'local.transferDocS': 'Déclaration de transfert document S',
    'local.numero9': 'Numéro 9',
    'local.numero9Price': 'Prix numéro 9',
    'local.numero4': 'Numéro 4',
    'local.numero4Price': 'Prix numéro 4',
    'local.tiCancellation': 'Annulation de TI',
    'local.declarationCancellation': 'Annulation de la déclaration S ou E',
    'local.transfer': 'Transfert',
    'local.declarationCancellationPrice': 'Prix d\'annulation de la déclaration S, E ou T',
    'local.fullScannedDocument': 'Full Scanned Document',
    'local.printService': 'Print Service',
    'local.next': 'Suivant',
    'local.documentsNote': 'Les documents suivants sont requis. Veuillez vous assurer qu\'ils sont valides et en bon état.',
    'local.fullCompanyNotice': 'Here we displayed all steps included local company completed from document 9 transfer, we exclude non-completed steps.',
    'local.modalBadge': 'Entreprise locale',
    'local.step1Label': 'Informations',
    'local.step2Label': 'Documents',
    'local.vendorCompanyPlaceholder': 'Saisir le nom de l\'entreprise vendeuse',
    'local.viewRecord': 'Voir le dossier',
    'local.editRecord': 'Modifier le dossier',
    'local.deleteModalTitle': 'Supprimer cette facture de service ?',
    'local.deleteTypeClientName': 'Saisissez le nom du client exactement pour confirmer la suppression.',
    'local.deleteNotAllowedAge': 'Ce dossier a plus de 30 jours — suppression réservée à un administrateur.',
    'local.deleteConfirm': 'Supprimer définitivement',

    // Transfer Document 9
    'transfer9.title': 'Gérer les Transferts du Document N°9',
    'transfer9.recipientName': 'Nom du destinataire/déclarant',
    'transfer9.destination': 'Destination',
    'transfer9.declarationEntry': 'Décl. Entrée ZF/FZ/Entrepôt',
    'transfer9.goodsDescription': 'Description de la Marchandise',
    'transfer9.destinationName': 'Nom du destinataire/déclarant',
    'transfer9.declaredValue': 'Valeur déclarée',
    'transfer9.addUpdate': 'Ajouter / modifier un transfert Document N°9',
    'transfer9.placeholderEnter': 'Saisir…',
    'transfer9.step1RequiredError': 'Indiquez le destinataire / déclarant et le nom du destinataire.',
    'transfer9.processOngoing': 'Le processus de ce formulaire est en cours.',
    'transfer9.requireAllSteps': 'Exiger toutes les étapes',
    'transfer9.codeNo': 'Code n°',
    'transfer9.licenseCode': 'Code de Licence',
    'transfer9.fzOperatorName': 'Nom de l\'opérateur de FZ/entrepôt',
    'transfer9.summitNumber': 'N° sommier/ répertoire',
    'transfer9.doNumber': 'D/O N°',
    'transfer9.entryQuantity': 'Quantité Entrée',
    'transfer9.vesselName': 'Nom du Bateau',
    'transfer9.arrivalDate': 'Date d\'arrivée',
    'transfer9.nifCode': 'Code Nif',
    'transfer9.shippingNumber': 'Connaissement n°',
    'transfer9.originCountry': 'Pays d\'Origine',
    'transfer9.voyageNumber': 'N° Voy',
    'transfer9.fiscalReg': 'Reg. fiscal',
    'transfer9.hsCode': 'Code HS',
    'transfer9.exitQuantity': 'Qté Sortie',
    'transfer9.grossWeight': 'Poids Bruts',
    'transfer9.exitPoint': 'Point Sortie',
    'transfer9.next': 'Suivant',
    'transfer9.finish': 'Terminer',
    'transfer9.actionsMenu': 'Actions sur la ligne',
    'transfer9.actionView': 'Voir',
    'transfer9.actionViewDocument': 'Voir le document',
    'transfer9.actionEdit': 'Modifier',
    'transfer9.actionDelete': 'Supprimer',
    'transfer9.actionDownloadPdf': 'Télécharger PDF',

    // Chamber Invoice
    'chamberInvoice.title': 'FACTURE DE CHAMBRE',
    'chamberInvoice.details': 'Commercial Invoice Details',
    'chamberInvoice.consignee': 'Consigné',
    'chamberInvoice.tin': 'TIN',
    'chamberInvoice.tel': 'TEL',
    'chamberInvoice.sourceDestination': 'Source/Destination',
    'chamberInvoice.commercialRelation': 'Relation Commerciale',
    'chamberInvoice.consignmentLocation': 'Lieu de Consignation',
    'chamberInvoice.invoiceNumber': 'Numéro de Facture',
    'chamberInvoice.invoiceDate': 'Date de Facture',
    'chamberInvoice.salesConditions': 'Conditions de Vente (Incoterm)',
    'chamberInvoice.purchaseOrder': 'Purchase Order',
    'chamberInvoice.appReferenceNumber': 'N° de Référence APP',
    'chamberInvoice.paymentConditions': 'Conditions de Paiement',
    'chamberInvoice.invoiceCurrency': 'Devise de la Facture',
    'chamberInvoice.expedition': 'Expédition',
    'chamberInvoice.swiftCode': 'Code SWIFT',
    'chamberInvoice.loadingPort': 'Port de Chargement',
    'chamberInvoice.finalDestination': 'Destination Finale',
    'chamberInvoice.bankDetails': 'Details Bancaires',
    'chamberInvoice.bankAccount': 'Compte Bancaire',
    'chamberInvoice.intermediateBank': 'InterMediate Bank',
    'chamberInvoice.currency': 'Currency',
    'chamberInvoice.goodsDescription': 'Description of Goods',
    'chamberInvoice.description': 'Description',
    'chamberInvoice.descriptionPlaceholder': 'ex. RBD PALM OIL 20 L — description complète',
    'chamberInvoice.hsCode': 'Code HS',
    'chamberInvoice.origin': 'Origin',
    'chamberInvoice.unit': 'Unit',
    'chamberInvoice.qty': 'Qty',
    'chamberInvoice.unitPrice': 'Unit Price (USD$)',
    'chamberInvoice.totalAmount': 'Total Amount (USD$)',

    // Performa
    'performa.title': 'Performa',
    'performa.addNew': 'Ajouter une nouvelle entrée',
    'performa.print': 'Imprimer',
    'performa.buyer': 'Acheteur',
    'performa.vendor': 'Vendeur',
    'performa.performaCode': 'Code Performa',
    'performa.tinNo': 'Tin no',
    'performa.addUpdate': 'Ajouter/Mettre à jour Performa',
    'performa.sourceDestination': 'Source et Destination',
    'performa.goodsTable': 'Table de description des marchandises',
    'performa.descriptionOfGoods': 'Description of Goods',
    'performa.hsCode': 'HS CODE',
    'performa.qty': 'Qty',
    'performa.unitPrice': 'Unit Price',
    'performa.totalUnitPrice': 'Total Unit Price',
    'performa.origin': 'Origine',
    'performa.expedition': 'Expédition',
    'performa.swiftCode': 'Code Swift',
    'performa.loadingPort': 'Port de chargement',
    'performa.finalDestination': 'Destination finale',
    'performa.payment': 'Paiement',
    'performa.bank': 'Banque',
    'performa.fiscalIdNumber': 'Numéro d\'identification fiscale',
    'performa.saveChanges': 'Enregistrer les modifications',

    // Customer File
    'customerFile.title': 'Gérer les fichiers clients',
    'customerFile.addNew': 'Ajouter Nouveau',
    'customerFile.customerName': 'Nom du client',
    'customerFile.fileNumber': 'NodulDossier',
    'customerFile.description': 'DescriptionID',
    'customerFile.fileType': 'TypedeDossier',
    'customerFile.billOfLading': 'BL',
    'customerFile.destination': 'DestinationID',
    'customerFile.createdBy': 'CreatedBy',
    'customerFile.addUpdate': 'Ajouter/Mettre à jour Fichier Client',
    'customerFile.rtaOperation': 'RTAOperation',
    'customerFile.transitNumber': 'TNumber',
    'customerFile.arrivalDate': 'ArrivalDate',
    'customerFile.loadingNumber': 'LNumber',
    'customerFile.freightForwarder': 'Transitaire',
    'customerFile.eslOperation': 'ESLOperation',
    'customerFile.taxId': 'TINNumber',
    'customerFile.voyageNumber': 'VoyageNo',
    'customerFile.receivedDate': 'ReceivedDate',
    'customerFile.shippingLine': 'ShippingLine',
    'customerFile.save': 'Enregistrer',

    // Certificate of Origin
    'certificateOrigin.title': 'Certificat d\'Origine',
    'certificateOrigin.addNew': 'Ajouter Nouveau',
    'certificateOrigin.client': 'Client',
    'certificateOrigin.description': 'Description',
    'certificateOrigin.destination': 'Destination',
    'certificateOrigin.hsCode': 'Code HS',
    'certificateOrigin.addUpdate': 'Ajouter/Mettre à jour le Certificat d\'Origine',
    'certificateOrigin.transportType': 'Type de transport',
    'certificateOrigin.originProduct': 'Produit d\'origine',
    'certificateOrigin.declarationForm': 'Formulaire de déclaration',
    'certificateOrigin.taxIdNif': 'N° d\'identification fiscale (NIF)',
    'certificateOrigin.telephone': 'Téléphone',
    'certificateOrigin.mt': 'MT',
    'certificateOrigin.grossWeight': 'Poids Brut',
    'certificateOrigin.save': 'Enregistrer',

    // Login
    'login.title': 'GEOSOM Transit',
    'login.sectorLabel': 'Transit & transport',
    'login.subtitle': 'Solution complète de gestion du transit pour la logistique, l\'entreposage et les opérations de livraison',
    'login.welcomeBack': 'Bon retour',
    'login.continueMessage': 'Veuillez vous connecter à votre compte pour continuer',
    'login.email': 'Adresse e-mail',
    'login.password': 'Mot de passe',
    'login.rememberMe': 'Se souvenir de moi',
    'login.forgotPassword': 'Mot de passe oublié?',
    'login.signIn': 'Se connecter',
    'login.signingIn': 'Connexion...',
    'login.invalidCredentials': 'Identifiants invalides. Veuillez réessayer.',
    'login.signInByKey': 'Se connecter par clé',

    // Dashboard
    'dashboard.monthlyRevenue': 'Revenu Mensuel',
    'dashboard.totalOrders': 'Total des Commandes',
    'dashboard.totalExpenses': 'Dépenses Totales',
    'dashboard.deliveredOrders': 'Commandes Livrées',
    'dashboard.completed': 'Terminé',
    'dashboard.pending': 'En attente',
    'dashboard.lastMonth': 'Mois dernier',
    'dashboard.increased': 'Augmenté',
    'dashboard.decreased': 'Diminué',
    'dashboard.employeeGenderDistribution': 'Distribution par Genre des Employés',
    'dashboard.female': 'Femme',
    'dashboard.male': 'Homme',
    'dashboard.residenceDistribution': 'Distribution par Résidence',
    'dashboard.citizen': 'Citoyen',
    'dashboard.foreign': 'Étranger',

    // Roles
    'roles.title': 'Gérer les rôles des utilisateurs',
    'roles.roleName': 'Nom du rôle',
    'roles.description': 'Description',
    'roles.addRole': 'Ajouter un nouveau rôle',
    'roles.editRole': 'Modifier le rôle',

    // Users
    'users.title': 'Gérer les utilisateurs',
    'users.username': 'Nom d\'utilisateur',
    'users.role': 'Rôle',
    'users.email': 'Email',
    'users.status': 'Statut',
    'users.active': 'Actif',

    // Configurations
    'config.baseSettings': 'Paramètres de base',
    'config.hrResources': 'Ressources humaines',
    'config.payroll': 'Paie',
    'config.presence': 'Présence',
    'config.auth': 'Authentifications',
    'config.security': 'Politique de compte et de sécurité',
    'config.external': 'Services externes',
    'config.manageApi': 'Gérer l\'API',
    'config.integrations': 'Intégrations',
    'config.deleteAccount': 'Supprimer le compte',
    'config.companyName': 'Nom de l\'entreprise',
    'config.address': 'Adresse',
    'config.phone': 'Numéro de téléphone de l\'entreprise',
    'config.freightRate': 'Tarif de fret',
    'config.units': 'Unités',
    'config.ciAmount': 'Montant CI actuel',
    'config.currency': 'Symbole monétaire',
    'config.decimals': 'Décimales',
    'config.employeePrefix': 'Préfixe d\'ID d\'employé',
    'config.welcomeMessage': 'Activer le message de bienvenue au démarrage',
    'config.djfRate': 'Taux de change Dollar vers DJF',
    'config.imageConfig': 'Configuration d\'Image',
    'config.letterHead': 'En-tête de lettre',
    'config.footerLogo': 'Logo de pied de page',
    'config.signatureLogo': 'Logo de signature',
    'config.chooseFile': 'Choisir un fichier',
    'config.noFileChosen': 'Aucun fichier choisi',
    'config.payrollTitle': 'Paramètres de Paie',
    'config.payrollStart': 'Jour de début de paie',
    'config.payrollEnd': 'Jour de fin de paie',
    'config.absenceThreshold': 'Seuil d\'absence élevé (par défaut 5)',
    'config.loginLimits': 'Activer les limites de connexion',
    'config.passwordExpiry': 'Activer l\'expiration du mot de passe',
    'config.detailedLogging': 'Activer la journalisation détaillée et les actions sensibles',

    // Profile
    'profile.superAdmin': 'Super Admin',
    'profile.logout': 'Déconnexion',
    'profile.english': 'Anglais',
    'profile.french': 'Français',
    'profile.arabic': 'Arabe',
    'layout.welcomeMessage': 'Nous sommes ravis de vous revoir ! Explorez votre tableau de bord pour les derniers indicateurs et actions.',
  },
  ar: {
    // Common
    'common.search': 'ابحث هنا',
    'common.loading': 'جار التحميل...',
    'common.show': 'عرض',
    'common.save': 'حفظ التغييرات',
    'common.cancel': 'إلغاء',
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.delete': 'حذف',
    'common.action': 'إجراء',
    'common.addNew': 'إضافة جديد',
    'common.noData': 'لا توجد بيانات متاحة في الجدول',
    'common.showing': 'عرض',
    'common.to': 'إلى',
    'common.of': 'من',
    'common.entries': 'إدخالات',
    'common.version': 'الإصدار: 2.0.0 / رئيسي',
    'common.copyright': '2025© حلول تقنيات جيوسوم.',
    'common.welcome': 'مرحبا',

    // Menu
    'menu.dashboard': 'لوحة القيادة',
    'menu.services': 'الخدمات',
    'menu.imports': 'الواردات',
    'menu.warehouses': 'المستودعات',
    'menu.transports': 'النقل',
    'menu.expenses': 'المصروفات',
    'menu.hr': 'الموارد البشرية',
    'menu.registration': 'التسجيل',
    'menu.reports': 'التقارير والتحليلات',
    'menu.settings': 'الإعدادات',
    'menu.roles': 'الأدوار',
    'menu.users': 'المستخدمون',
    'menu.configurations': 'التكوينات',
    'menu.commercial-chamber': 'الغرفة التجارية',
    'menu.local-company': 'الشركة المحلية',
    'menu.transfer-document-9': 'نقل الوثيقة رقم 9',
    'menu.chamber-invoice': 'فاتورة الغرفة',
    'menu.performa': 'النموذج',
    'menu.customer-file': 'ملف العميل',
    'menu.certificate-origin': 'شهادة المنشأ',
    'menu.suppliers': 'الموردون',
    'menu.orders': 'الطلبات',
    'menu.order-verification': 'التحقق من الطلب',
    'menu.order-reception': 'استلام الطلب',
    'menu.delivered-orders': 'الطلبات المسلمة',
    'menu.document-9': 'الوثيقة رقم 9',
    'menu.document-4': 'الوثيقة رقم 4',
    'menu.clearance': 'التخليص',
    'menu.invoice-report': 'تقرير الفاتورة',
    'menu.products': 'المنتجات',
    'menu.inventories': 'المخزونات',
    'menu.warehouse': 'المستودع',
    'menu.carriers': 'شركات النقل',
    'menu.associations': 'الجمعيات',
    'menu.carrier-mode': 'وضع النقل',
    'menu.routes': 'المسارات',
    'menu.shipping-lines': 'خطوط الشحن',
    'menu.logistics-files-operations': 'ملفات اللوجستيات / العمليات',
    'menu.transportation-management': 'إدارة النقل',
    'menu.bulk-transportation-management': 'إدارة النقل بالشحن السائب',
    'menu.car-reservations': 'حجوزات المركبات',
    'menu.fleet-management': 'إدارة الأسطول',
    'menu.transport-expense-requests': 'طلبات المصروفات',
    'menu.purchase-management': 'إدارة المشتريات',
    'menu.sales-management': 'إدارة المبيعات',
    'menu.accounting-system': 'النظام المحاسبي',
    'menu.transport-reporting-analytics': 'التقارير والتحليلات',
    'menu.transport-configuration-admin': 'التكوين والإدارة',
    'transport.modulePlaceholder': 'سيُعرض محتوى هذا القسم هنا.',
    'menu.expense-categories': 'فئات المصروفات',
    'menu.expense': 'المصروف',
    'menu.expense-allocation': 'تخصيص المصروفات',
    'menu.other-expenses': 'مصروفات أخرى',
    'menu.maritime-lines': 'الخطوط البحرية',
    'menu.personnel-file': 'ملف الموظفين',
    'menu.payroll': 'كشف الرواتب',
    'menu.leave-management': 'إدارة الإجازات',
    'menu.attendance-management': 'إدارة الحضور',
    'menu.clients': 'العملاء',
    'clients.pageTitle': 'إدارة العملاء',
    'clients.addButton': 'إضافة عميل جديد',
    'clients.show': 'عرض',
    'clients.entries': 'سجلات',
    'clients.searchLabel': 'بحث:',
    'clients.colCompany': 'الشركة',
    'clients.colName': 'الاسم',
    'clients.colEmail': 'البريد',
    'clients.colPhone': 'الهاتف',
    'clients.colAddress': 'العنوان',
    'clients.colAction': 'إجراء',
    'clients.empty': 'لا توجد بيانات',
    'clients.modalTitle': 'إضافة / تعديل عميل',
    'clients.fieldName': 'اسم العميل',
    'clients.fieldCompany': 'اسم الشركة',
    'clients.fieldEmail': 'البريد الإلكتروني',
    'clients.fieldPhone': 'الهاتف',
    'clients.fieldAddress': 'العنوان',
    'clients.save': 'حفظ',
    'clients.selectClient': 'اختر عميلاً',
    'menu.bank': 'البنك',
    'menu.item-prices': 'أسعار المواد',
    'menu.goods-categories': 'فئات البضائع',
    'menu.companies': 'الشركات',
    'menu.import-reports': 'تقارير الاستيراد',
    'menu.hr-reports': 'تقارير الموارد البشرية',
    'menu.financial-reports': 'التقارير المالية',
    'menu.services-reports': 'تقرير الخدمات',

    // Financial Reports
    'financial.title': 'التقارير المالية',
    'financial.subtitle': 'جميع التقارير المحددة',
    'financial.expenseReport': 'تقرير المصروفات',
    'financial.expenseReportDesc': 'عرض وتحليل جميع معاملات المصروفات.',
    'financial.allocationReport': 'ملخص تخصيص المصروفات',
    'financial.allocationReportDesc': 'عرض وتحليل تقرير تخصيص المصروفات.',
    'financial.profitReport': 'ملخص الربح الشهري',
    'financial.profitReportDesc': 'عرض وتحليل إيرادات الخدمات الشهرية والمصروفات والأرباح.',
    'financial.backToReports': '← العودة إلى التقارير',
    'financial.expenseReportTitle': 'تقرير المصروفات',
    'financial.viewAnalysis': 'عرض التحليلات',
    'financial.print': 'طباعة',
    'financial.dateRange': 'نطاق التاريخ',
    'financial.expenseCategories': 'فئات المصروفات',
    'financial.expenseType': 'نوع المصروف',
    'financial.search': 'بحث',
    'financial.all': 'الكل',
    'financial.type': 'النوع',
    'financial.category': 'الفئة',
    'financial.expense': 'المصروف',
    'financial.amount': 'المبلغ',
    'financial.amountUSD': 'المبلغ (دولار)',
    'financial.description': 'الوصف',
    'financial.status': 'الحالة',
    'financial.date': 'التاريخ',
    'financial.total': 'الإجمالي:',
    'financial.noExpenses': 'لا توجد مصروفات',
    'financial.allocationTitle': 'تقرير المصروفات',
    'financial.viewDetail': 'عرض التفاصيل',
    'financial.printSummary': 'طباعة التقرير الموجز',
    'financial.month': 'الشهر',
    'financial.totalExpenses': 'إجمالي المصروفات',
    'financial.totalAllocation': 'إجمالي التخصيص',
    'financial.balance': 'الرصيد',
    'financial.action': 'الإجراء',
    'financial.profitTitle': 'ملخص الربح الشهري',
    'financial.year': 'السنة:',
    'financial.totalServices': 'إجمالي الخدمات',
    'financial.totalHRExpenses': 'إجمالي مصروفات الموارد البشرية',
    'financial.profit': 'الربح',
    'financial.percentage': '% النسبة المئوية',
    'financial.overallTotal': 'الإجمالي الكلي:',

    // Services Reports
    'services.title': 'تقارير الخدمات',
    'services.subtitle': 'جميع التقارير المحددة',
    'services.localCompanyReport': 'تقرير الشركة المحلية',
    'services.localCompanyDesc': 'يقدم هذا التقرير تفاصيل حول الشركة المحلية.',
    'services.chamberServices': 'خدمات الغرفة',
    'services.chamberServicesDesc': 'يوفر معلومات مفصلة حول خدمات الغرفة.',
    'services.backToReports': '← العودة إلى التقارير',
    'services.ordersReport': 'تقرير الطلبات',
    'services.dateRange': 'نطاق التاريخ',
    'services.client': 'العميل',
    'services.search': 'بحث',
    'services.ref': 'المرجع',
    'services.mobile': 'الهاتف',
    'services.goodsDescription': 'وصف البضائع',
    'services.serviceFee': 'رسوم الخدمة',
    'services.creationDate': 'تاريخ الإنشاء',
    'services.createdBy': 'أنشئ بواسطة',
    'services.action': 'الإجراء',
    'services.total': 'الإجمالي:',
    'services.localCompanyTitle': 'تقرير الشركة المحلية',
    'services.sellingCompany': 'الشركة البائعة',
    'services.sourceDestination': 'المصدر والوجهة',
    'services.descriptionOfGoods': 'وصف البضائع',
    'services.fileFee': 'رسوم الملف',
    'services.truckQuantity': 'كمية تحميل الشاحنة',
    'services.totalProfit': 'إجمالي الربح',

    // Commercial Chamber
    'commercial.title': 'إدارة القائمة التجارية',
    'commercial.client': 'العميل',
    'commercial.responsible': 'المسؤول',
    'commercial.goodsDescription': 'وصف البضائع',
    'commercial.servicesTotal': 'إجمالي الخدمات',
    'commercial.serviceCharge': 'رسوم الخدمة',
    'commercial.bankFee': 'رسوم البنك',
    'commercial.transport': 'النقل',
    'commercial.total': 'الإجمالي',
    'commercial.createdBy': 'أنشأ بواسطة',
    'commercial.print': 'طباعة',
    'commercial.addUpdate': 'إضافة/تحديث تجاري',
    'commercial.editEntry': 'تعديل السجل التجاري',
    'commercial.commercialInvoiceNo': 'رقم الفاتورة التجارية',
    'commercial.commercialInvoiceDate': 'تاريخ الفاتورة التجارية',
    'commercial.purchaseOrderNo': 'رقم أمر الشراء',
    'commercial.purchaseOrderDate': 'تاريخ أمر الشراء',
    'commercial.chamberServiceAmount': 'مبلغ خدمة الغرفة',
    'commercial.quantity': 'الكمية',
    'commercial.unitPrice': 'سعر الوحدة للفاتورة التجارية',
    'commercial.percentage': 'النسبة المئوية %',
    'commercial.tell': 'تيل',
    'commercial.timno': 'تيمنو',
    'commercial.customerDocument': 'وثيقة العميل',
    'commercial.chamberDocument': 'وثيقة الغرفة',
    'commercial.chamberInvoice': 'فاتورة الغرفة',
    'commercial.commercialInvoice': 'الفاتورة التجارية',
    'commercial.packingList': 'قائمة التعبئة',
    'commercial.truckWayBill': 'بوليصة شحن الشاحنة',
    'commercial.originalCertificate': 'الشهادة الأصلية',
    'commercial.certificateFee': 'رسوم الشهادة',
    'commercial.chooseFile': 'اختر ملف',
    'commercial.previous': 'السابق',
    'commercial.next': 'التالي',
    'commercial.finish': 'إنهاء',
    'commercial.pageSubtitle': 'متابعة الملفات والمبالغ بالفرنك الجيبوتي والوثائق المرتبطة.',
    'commercial.modalBadge': 'الغرفة التجارية',
    'commercial.step1Label': 'بيانات الملف',
    'commercial.step2Label': 'المستندات',
    'commercial.optionalDocumentsNote':
      'ملاحظة: المستندات التالية اختيارية. تأكد من صحتها وحالتها.',
    'commercial.responsiblePlaceholder': 'اسم المسؤول',

    // Local Company
    'local.title': 'إدارة قائمة الشركات المحلية',
    'local.localCompany': 'الشركة المحلية',
    'local.fullLocalCompany': 'الشركة المحلية الكاملة',
    'local.client': 'العميل',
    'local.sourceDestination': 'المصدر والوجهة',
    'local.vendorCompany': 'اسم الشركة البائعة',
    'local.goodsDescription': 'وصف البضائع',
    'local.purchasingCompany': 'الشركة المشترية',
    'local.fileFee': 'رسوم الملف',
    'local.quantity': 'الكمية',
    'local.truckLoadingQuantity': 'كمية تحميل الشاحنة',
    'local.addUpdate': 'إضافة/تحديث الشركة المحلية',
    'local.closureDate': 'تاريخ الإغلاق',
    'local.billOfLoading': 'بوليصة الشحن',
    'local.declarationS': 'الإقرار S',
    'local.declarationE': 'الإقرار E',
    'local.transitFee': 'رسوم العبور',
    'local.serviceFee': 'رسوم الخدمة',
    'local.escortFee': 'رسوم المرافقة',
    'local.total': 'الإجمالي',
    'local.deliveryOrder': 'أمر التسليم',
    'local.transferDocS': 'وثيقة نقل S',
    'local.numero9': 'رقم 9',
    'local.numero9Price': 'سعر رقم 9',
    'local.numero4': 'رقم 4',
    'local.numero4Price': 'سعر رقم 4',
    'local.tiCancellation': 'إلغاء TI',
    'local.declarationCancellation': 'إلغاء الإقرار S أو E',
    'local.transfer': 'النقل',
    'local.declarationCancellationPrice': 'سعر إلغاء الإقرار S أو E أو T',
    'local.fullScannedDocument': 'وثيقة ممسوحة كاملة',
    'local.printService': 'طباعة الخدمة',
    'local.next': 'التالي',
    'local.documentsNote': 'المستندات التالية مطلوبة. يرجى التأكد من صحتها وحالتها الجيدة.',
    'local.fullCompanyNotice': 'هنا نعرض جميع الخطوات المكتملة للشركة المحلية من نقل الوثيقة 9، ونستبعد الخطوات غير المكتملة.',
    'local.modalBadge': 'الشركة المحلية',
    'local.step1Label': 'البيانات',
    'local.step2Label': 'المستندات',
    'local.vendorCompanyPlaceholder': 'أدخل اسم الشركة البائعة',
    'local.viewRecord': 'عرض السجل',
    'local.editRecord': 'تعديل السجل',
    'local.deleteModalTitle': 'حذف فاتورة الخدمة هذه؟',
    'local.deleteTypeClientName': 'اكتب اسم العميل حرفياً لتأكيد الحذف.',
    'local.deleteNotAllowedAge': 'هذا السجل أقدم من 30 يوماً — الحذف محجوز للمسؤول.',
    'local.deleteConfirm': 'حذف نهائي',

    // Transfer Document 9
    'transfer9.title': 'إدارة نقل الوثيقة رقم 9',
    'transfer9.recipientName': 'اسم المستلم/المصرح',
    'transfer9.destination': 'الوجهة',
    'transfer9.declarationEntry': 'إقرار الدخول ZF/FZ/المستودع',
    'transfer9.goodsDescription': 'وصف البضائع',
    'transfer9.destinationName': 'اسم الوجهة/المصرح',
    'transfer9.declaredValue': 'القيمة المصرح بها',
    'transfer9.addUpdate': 'إضافة/تحديث نقل رقم 9',
    'transfer9.placeholderEnter': 'أدخل…',
    'transfer9.step1RequiredError': 'يرجى إدخال المستلم/المصرح واسم الوجهة.',
    'transfer9.processOngoing': 'عملية هذا النموذج جارية حاليًا.',
    'transfer9.requireAllSteps': 'تطلب جميع الخطوات',
    'transfer9.codeNo': 'رقم الكود',
    'transfer9.licenseCode': 'رمز الترخيص',
    'transfer9.fzOperatorName': 'اسم مشغل المنطقة الحرة/المستودع',
    'transfer9.summitNumber': 'رقم القمة/الدليل',
    'transfer9.doNumber': 'رقم D/O',
    'transfer9.entryQuantity': 'كمية الدخول',
    'transfer9.vesselName': 'اسم السفينة',
    'transfer9.arrivalDate': 'تاريخ الوصول',
    'transfer9.nifCode': 'رمز NIF',
    'transfer9.shippingNumber': 'رقم الشحن',
    'transfer9.originCountry': 'بلد المنشأ',
    'transfer9.voyageNumber': 'رقم الرحلة',
    'transfer9.fiscalReg': 'التسجيل المالي',
    'transfer9.hsCode': 'رمز HS',
    'transfer9.exitQuantity': 'كمية الخروج',
    'transfer9.grossWeight': 'الوزن الإجمالي',
    'transfer9.exitPoint': 'نقطة الخروج',
    'transfer9.next': 'التالي',
    'transfer9.finish': 'إنهاء',
    'transfer9.actionsMenu': 'إجراءات السطر',
    'transfer9.actionView': 'عرض',
    'transfer9.actionViewDocument': 'عرض المستند',
    'transfer9.actionEdit': 'تعديل',
    'transfer9.actionDelete': 'حذف',
    'transfer9.actionDownloadPdf': 'تنزيل PDF',

    // Chamber Invoice
    'chamberInvoice.title': 'فاتورة الغرفة',
    'chamberInvoice.details': 'تفاصيل الفاتورة التجارية',
    'chamberInvoice.consignee': 'المرسل إليه',
    'chamberInvoice.tin': 'رقم التعريف الضريبي',
    'chamberInvoice.tel': 'الهاتف',
    'chamberInvoice.sourceDestination': 'المصدر/الوجهة',
    'chamberInvoice.commercialRelation': 'العلاقة التجارية',
    'chamberInvoice.consignmentLocation': 'موقع الشحنة',
    'chamberInvoice.invoiceNumber': 'رقم الفاتورة',
    'chamberInvoice.invoiceDate': 'تاريخ الفاتورة',
    'chamberInvoice.salesConditions': 'شروط البيع (Incoterm)',
    'chamberInvoice.purchaseOrder': 'أمر الشراء',
    'chamberInvoice.appReferenceNumber': 'رقم المرجع APP',
    'chamberInvoice.paymentConditions': 'شروط الدفع',
    'chamberInvoice.invoiceCurrency': 'عملة الفاتورة',
    'chamberInvoice.expedition': 'الشحن',
    'chamberInvoice.swiftCode': 'رمز SWIFT',
    'chamberInvoice.loadingPort': 'ميناء التحميل',
    'chamberInvoice.finalDestination': 'الوجهة النهائية',
    'chamberInvoice.bankDetails': 'تفاصيل البنك',
    'chamberInvoice.bankAccount': 'الحساب البنكي',
    'chamberInvoice.intermediateBank': 'البنك الوسيط',
    'chamberInvoice.currency': 'العملة',
    'chamberInvoice.goodsDescription': 'وصف البضائع',
    'chamberInvoice.description': 'الوصف',
    'chamberInvoice.descriptionPlaceholder': 'مثال: زيت النخيل — الوصف الكامل',
    'chamberInvoice.hsCode': 'رمز HS',
    'chamberInvoice.origin': 'المنشأ',
    'chamberInvoice.unit': 'الوحدة',
    'chamberInvoice.qty': 'الكمية',
    'chamberInvoice.unitPrice': 'سعر الوحدة (دولار)',
    'chamberInvoice.totalAmount': 'المبلغ الإجمالي (دولار)',

    // Performa
    'performa.title': 'النموذج',
    'performa.addNew': 'إضافة إدخال جديد',
    'performa.print': 'طباعة',
    'performa.buyer': 'المشتري',
    'performa.vendor': 'البائع',
    'performa.performaCode': 'رمز النموذج',
    'performa.tinNo': 'رقم التعريف الضريبي',
    'performa.addUpdate': 'إضافة/تحديث النموذج',
    'performa.sourceDestination': 'المصدر والوجهة',
    'performa.goodsTable': 'جدول وصف البضائع',
    'performa.descriptionOfGoods': 'وصف البضائع',
    'performa.hsCode': 'رمز HS',
    'performa.qty': 'الكمية',
    'performa.unitPrice': 'سعر الوحدة',
    'performa.totalUnitPrice': 'السعر الإجمالي للوحدة',
    'performa.origin': 'المنشأ',
    'performa.expedition': 'الشحن',
    'performa.swiftCode': 'رمز سويفت',
    'performa.loadingPort': 'ميناء التحميل',
    'performa.finalDestination': 'الوجهة النهائية',
    'performa.payment': 'الدفع',
    'performa.bank': 'البنك',
    'performa.fiscalIdNumber': 'رقم التعريف الضريبي',
    'performa.saveChanges': 'حفظ التغييرات',

    // Customer File
    'customerFile.title': 'إدارة ملفات العملاء',
    'customerFile.addNew': 'إضافة جديد',
    'customerFile.customerName': 'اسم العميل',
    'customerFile.fileNumber': 'رقم الملف',
    'customerFile.description': 'الوصف',
    'customerFile.fileType': 'نوع الملف',
    'customerFile.billOfLading': 'بوليصة الشحن',
    'customerFile.destination': 'الوجهة',
    'customerFile.createdBy': 'تم الإنشاء بواسطة',
    'customerFile.addUpdate': 'إضافة/تحديث ملف العميل',
    'customerFile.rtaOperation': 'عملية RTA',
    'customerFile.transitNumber': 'رقم الترانزيت',
    'customerFile.arrivalDate': 'تاريخ الوصول',
    'customerFile.loadingNumber': 'رقم التحميل',
    'customerFile.freightForwarder': 'وكيل الشحن',
    'customerFile.eslOperation': 'عملية ESL',
    'customerFile.taxId': 'الرقم الضريبي',
    'customerFile.voyageNumber': 'رقم الرحلة',
    'customerFile.receivedDate': 'تاريخ الاستلام',
    'customerFile.shippingLine': 'خط الشحن',
    'customerFile.save': 'حفظ',

    // Certificate of Origin
    'certificateOrigin.title': 'شهادة المنشأ',
    'certificateOrigin.addNew': 'إضافة جديد',
    'certificateOrigin.client': 'العميل',
    'certificateOrigin.description': 'الوصف',
    'certificateOrigin.destination': 'الوجهة',
    'certificateOrigin.hsCode': 'رمز HS',
    'certificateOrigin.addUpdate': 'إضافة/تحديث شهادة المنشأ',
    'certificateOrigin.transportType': 'نوع النقل',
    'certificateOrigin.originProduct': 'منتج المنشأ',
    'certificateOrigin.declarationForm': 'نموذج التصريح',
    'certificateOrigin.taxIdNif': 'الرقم الضريبي (NIF)',
    'certificateOrigin.telephone': 'الهاتف',
    'certificateOrigin.mt': 'طن متري',
    'certificateOrigin.grossWeight': 'الوزن الإجمالي',
    'certificateOrigin.save': 'حفظ',

    // Login
    'login.title': 'GEOSOM Transit',
    'login.sectorLabel': 'النقل والترانزيت',
    'login.subtitle': 'حل إدارة شامل للنقل والخدمات اللوجستية والتخزين وعمليات التسليم',
    'login.welcomeBack': 'مرحبا بعودتك',
    'login.continueMessage': 'يرجى تسجيل الدخول إلى حسابك للمتابعة',
    'login.email': 'عنوان البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.rememberMe': 'تذكرني',
    'login.forgotPassword': 'هل نسيت كلمة المرور؟',
    'login.signIn': 'تسجيل الدخول',
    'login.signingIn': 'جاري تسجيل الدخول...',
    'login.invalidCredentials': 'بيانات الدخول غير صحيحة. حاول مرة أخرى.',
    'login.signInByKey': 'تسجيل الدخول بالمفتاح',

    // Dashboard
    'dashboard.monthlyRevenue': 'الإيرادات الشهرية',
    'dashboard.totalOrders': 'إجمالي الطلبات',
    'dashboard.totalExpenses': 'إجمالي المصروفات',
    'dashboard.deliveredOrders': 'الطلبات المسلمة',
    'dashboard.completed': 'مكتمل',
    'dashboard.pending': 'قيد الانتظار',
    'dashboard.lastMonth': 'الشهر الماضي',
    'dashboard.increased': 'زيادة',
    'dashboard.decreased': 'انخفاض',
    'dashboard.employeeGenderDistribution': 'توزيع الموظفين حسب الجنس',
    'dashboard.female': 'أنثى',
    'dashboard.male': 'ذكر',
    'dashboard.residenceDistribution': 'توزيع الإقامة',
    'dashboard.citizen': 'مواطن',
    'dashboard.foreign': 'أجنبي',

    // Roles
    'roles.title': 'إدارة أدوار المستخدمين',
    'roles.roleName': 'اسم الدور',
    'roles.description': 'الوصف',
    'roles.addRole': 'إضافة دور جديد',
    'roles.editRole': 'تعديل الدور',

    // Users
    'users.title': 'إدارة المستخدمين',
    'users.username': 'اسم المستخدم',
    'users.role': 'الدور',
    'users.email': 'البريد الإلكتروني',
    'users.status': 'الحالة',
    'users.active': 'نشط',

    // Configurations
    'config.baseSettings': 'الإعدادات الأساسية',
    'config.hrResources': 'الموارد البشرية',
    'config.payroll': 'الرواتب',
    'config.presence': 'الحضور',
    'config.auth': 'المصادقات',
    'config.security': 'سياسة الحساب والأمان',
    'config.external': 'الخدمات الخارجية',
    'config.manageApi': 'إدارة API',
    'config.integrations': 'التكاملات',
    'config.deleteAccount': 'حذف الحساب',
    'config.companyName': 'اسم الشركة',
    'config.address': 'العنوان',
    'config.phone': 'رقم هاتف الشركة',
    'config.freightRate': 'معدل الشحن',
    'config.units': 'الوحدات',
    'config.ciAmount': 'مبلغ CI الحالي',
    'config.currency': 'رمز العملة',
    'config.decimals': 'الكسور العشرية',
    'config.employeePrefix': 'بادئة معرف الموظف',
    'config.welcomeMessage': 'تفعيل رسالة الترحيب عند بدء التشغيل',
    'config.djfRate': 'سعر صرف الدولار إلى DJF',
    'config.imageConfig': 'تكوين الصورة',
    'config.letterHead': 'ترويسة الرسالة',
    'config.footerLogo': 'شعار التذييل',
    'config.signatureLogo': 'شعار التوقيع',
    'config.chooseFile': 'اختر ملف',
    'config.noFileChosen': 'لم يتم اختيار ملف',
    'config.payrollTitle': 'إعدادات الرواتب',
    'config.payrollStart': 'يوم بداية الراتب',
    'config.payrollEnd': 'يوم نهاية الراتب',
    'config.absenceThreshold': 'عتبة الغياب العالية (افتراضي 5)',
    'config.loginLimits': 'تفعيل حدود تسجيل الدخول',
    'config.passwordExpiry': 'تفعيل انتهاء صلاحية كلمة المرور',
    'config.detailedLogging': 'تفعيل السجل التفصيلي والإجراءات الحساسة',

    // Profile
    'profile.superAdmin': 'مسؤول عام',
    'profile.logout': 'تسجيل الخروج',
    'profile.english': 'الإنجليزية',
    'profile.french': 'الفرنسية',
    'profile.arabic': 'العربية',
    'layout.welcomeMessage': 'يسعدنا عودتك! استكشف لوحة التحكم للحصول على أحدث المؤشرات والإجراءات.',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
    if (storedLanguage === 'en' || storedLanguage === 'fr' || storedLanguage === 'ar') {
      return storedLanguage;
    }
    return 'fr';
  });

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
